#ifndef CONSOLEOUTPUTCOLORS_H_
#define CONSOLEOUTPUTCOLORS_H_

#define PASSED_OUTPUT_COLOR "\033[0;32m"
#define FAILED_OUTPUT_COLOR "\033[0;31m"
#define DEFAULT_OUTPUT_COLOR "\033[0m"

#endif /* CONSOLEOUTPUTCOLORS_H_ */
